# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 301)
        MainWindow.setStyleSheet("background-color:rgb(45, 48, 50);\n"
                                 "font: 12pt \"Terminator Two\";\n"
                                 "color:white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.archive_btn = QtWidgets.QPushButton(self.centralwidget)
        self.archive_btn.setGeometry(QtCore.QRect(10, 20, 431, 41))
        self.archive_btn.setStyleSheet("border:none;background-color:rgb(48, 105, 221);border-radius:5px")
        self.archive_btn.setObjectName("archive_btn")
        self.result_btn = QtWidgets.QPushButton(self.centralwidget)
        self.result_btn.setGeometry(QtCore.QRect(10, 70, 431, 41))
        self.result_btn.setStyleSheet("border:none;background-color:rgb(48, 105, 221);border-radius:5px")
        self.result_btn.setObjectName("result_btn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 170, 431, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
                                       "border-radius:5px;\n"
                                       "font: 12pt \"Terminator Two\";\n"
                                       "color:white;\n"
                                       "background-color:rgb(162, 162, 162);\n"
                                       "}\n"
                                       "\n"
                                       "QProgressBar::chunk{\n"
                                       "background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(0, 107, 217, 255), stop:0.710227 rgba(40, 255, 255, 255));border-radius:5px;\n"
                                       "}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 260, 431, 21))
        self.result_label.setText("")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn.setGeometry(QtCore.QRect(10, 210, 431, 41))
        self.quit_btn.setStyleSheet("border:none;background-color:rgb(255, 83, 106);border-radius:5px")
        self.quit_btn.setObjectName("quit_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(10, 120, 431, 41))
        self.start_btn.setStyleSheet("border:none;background-color:rgb(113, 221, 131);border-radius:5px")
        self.start_btn.setObjectName("start_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.archive_btn.setText(_translate("MainWindow", "select archiving directory"))
        self.result_btn.setText(_translate("MainWindow", "select result directory"))
        self.quit_btn.setText(_translate("MainWindow", "quit"))
        self.start_btn.setText(_translate("MainWindow", "start"))
